<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_confirm_password</name>
   <tag></tag>
   <elementGuidId>6fffdd34-cd5d-4039-8e36-9d723ad672f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-confirm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
