<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_lastname</name>
   <tag></tag>
   <elementGuidId>008f926f-0b4d-417a-8bdb-becb2fa9c75f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-lastname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
