<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_firstname</name>
   <tag></tag>
   <elementGuidId>b453b07f-30df-4160-8be0-6050330b2cd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#input-firstname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-firstname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
