<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_no</name>
   <tag></tag>
   <elementGuidId>c852f282-c4b3-4bd5-a48c-b48a3cb3b7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-newsletter-no</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
