<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_yes</name>
   <tag></tag>
   <elementGuidId>2b2103c1-b93f-4410-b82d-4ab3b0aabe32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='input-newsletter-yes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-newsletter-yes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
